repo_url: https://github.com/mdsreq-fga-unb/2025.1-T02-MeuCapilar
repo_name: 2025.1-T02-MeuCapilar


site_name: Meu Capilar

nav:
   - Home: index.md
   - Visão do produto e projeto:
      - 1.Cenário atual do cliente e do negócio: unidade1/sessao1.md
      - 2.Solução proposta: unidade1/sessao2.md
      - 3.Estrategias de Engenharia de Software: unidade1/sessao3.md
      - 4.Engenharia de Requisitos: unidade2/sessao4.md
      - 5.Cronogramas e Entregas: unidade1/sessao5.md
      - 6.Interação entre Equipe e Cliente: unidade1/sessao6.md
      - 7.Lista de Requisitos: unidade2/sessao7.md
      - 8.DoR e DoD: unidade2/sessao8.md
      - 9.Product Backlog: unidade2/sessao9.md
   - PBB e BDD: unidade3/PBB.md
   - USM: unidade3/USM.md
   - Casos de Uso:
      - Verify Contexto e Diagrama de Caso de Uso: unidade4/diagrama.md
      - Especificação 1: unidade4/esp_analisar_conteudo_manualmente.md
      - Especificação 2: unidade4/esp_auditar_conteudos.md
      - Especificação 3: unidade4/esp_supervisionar_interacoes.md
   - Lições Aprendidas: unidade1/licoesAprendidas.md
   - Atas e Gravações das Sprints:
      - Sprint 1:
        - Planning: sprints/sprint01/planning.md
        - Daily 1: sprints/sprint01/daily1.md
        - Daily 2: sprints/sprint01/daily2.md
        - Review: sprints/sprint01/review.md
        - Retrospectiva: sprints/sprint01/retrospective.md
      - Sprint 2: 
        - Planning: sprints/sprint02/planning.md
        - Daily 1: sprints/sprint02/daily1.md
        - Review: sprints/sprint02/review.md
        - Retrospectiva: sprints/sprint02/retrospective.md
      - Sprint 3:
         - Planning: sprints/sprint03/planning.md
         - Review: sprints/sprint03/review.md
         - Retrospectiva: sprints/sprint03/retrospective.md
   - Evidências de ESW e ER:
      - Wireframes: evidencias/wireframes.md
      - Projects: evidencias/projects.md

theme:
   name: material 
   palette:
    - scheme: default
      toggle: 
         icon: material/toggle-switch-off-outline
         name: Dark mode
      primary: pink
    - scheme: slate
      toggle:
         icon: material/toggle-switch
         name: Light mode
      primary: pink