repo_url: https://github.com/mdsreq-fga-unb/2025.1-T02-MeuCapilar
repo_name: 2025.1-T02-MeuCapilar


site_name: Meu Capilar

nav:
   - Home: index.md
   - Visão do produto e projeto:
      - Cenário atual do cliente e do negócio: unidade1/sessao1.md
      - Solução proposta: unidade1/sessao2.md
      - Estrategias de Engenharia de Software: unidade1/sessao3.md
      - Engenharia de Requisitos: unidade2/engeRequisitos.md
      - Cronogramas e Entregas: unidade1/sessao5.md
      - Interação entre Equipe e Cliente: unidade1/sessao6.md
   - Backlog:
      - Lista de Requisitos: backlog/sessao7.md
      - User Stories: backlog/userStories.md
      - DoR e DoD: backlog/sessao8.md
   - Lições Aprendidas: 
         - Unidade I: unidade1/licoesAprendidas.md
   - Sprints:
      - Sprint 2: 
        - Planning: sprints/sprint02/planning.md
        - Daily 1: sprints/sprint02/daily1.md

theme:
   name: material 
   palette:
    - scheme: default
      toggle: 
         icon: material/toggle-switch-off-outline
         name: Dark mode
      primary: pink
    - scheme: slate
      toggle:
         icon: material/toggle-switch
         name: Light mode
      primary: pink