default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] || "localhost" %>
  pool: 5

development:
  <<: *default
  database: meu_capilar_development

test:
  <<: *default
  database: meu_capilar_test
